services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_started
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/web/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - app
    ports:
      - 8002:80
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - app
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.4.4
    restart: unless-stopped
    user: root
    ports:
      - "${DB_HOST_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app
volumes:
  app:
  db:
networks:
  app:
